version: 2.1
orbs:
    slack: circleci/slack@3.4.2
    aws-cli: circleci/aws-cli@1.2.1
commands:
    node-install:
        steps:
            - run: npm ci
    node-linter:
        steps:
            - run: npm run lint -- --format html --output-file ./coverage/lint/index.html
            - store_artifacts:
                path: ./coverage
    npm-deploy:
        steps:
            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            - run: npm version $CIRCLE_TAG --allow-same-version --no-git-tag-version
            - run: npm publish
    slack-status:
        steps:
            - slack/status:
                mentions: '${CIRCLE_USERNAME}, version=$CIRCLE_TAG'
jobs:
    install-build-deploy:
        docker:
            - image: node:12
        steps:
            - checkout
            - node-install
            - node-linter
            - npm-deploy
            - slack-status
workflows:
    install-build-deploy:
        jobs:
            - install-build-deploy:
                context:
                    - tools-cicd
                    - npm-org-token
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
